// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function Counter(Props) {
  var match = React.useReducer((function (state, action) {
          if (!action) {
            return {
                    count: state.count + 1 | 0
                  };
          }
          var match = state.count;
          if (match !== 0) {
            return {
                    count: state.count - 1 | 0
                  };
          } else {
            return {
                    count: 0
                  };
          }
        }), {
        count: 0
      });
  var dispatch = match[1];
  return React.createElement("div", {
              className: "container"
            }, React.createElement("h3", {
                  className: "w-auto ml-10 text-2xl"
                }, String(match[0].count)), React.createElement("button", {
                  className: "button m-2 border p-2 shadow-md",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Inc */0);
                    })
                }, "+"), React.createElement("button", {
                  className: "button m-2 border p-2 shadow-md",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Dec */1);
                    })
                }, "-"));
}

var make = Counter;

export {
  make ,
  
}
/* react Not a pure module */
