// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Modal$ReasonHasuraDemo = require("./components/Modal.bs.js");
var Header$ReasonHasuraDemo = require("./components/Header.bs.js");
var Counter$ReasonHasuraDemo = require("./components/Counter.bs.js");
var PostsList$ReasonHasuraDemo = require("./components/PostsList.bs.js");

function App(Props) {
  var match = React.useReducer((function (param, action) {
          if (action) {
            return {
                    isModalOpened: false
                  };
          } else {
            return {
                    isModalOpened: true
                  };
          }
        }), {
        isModalOpened: false
      });
  var dispatch = match[1];
  var state = match[0];
  return React.createElement("div", {
              onClick: (function (param) {
                  return Curry._1(dispatch, /* Close */1);
                })
            }, React.createElement(Header$ReasonHasuraDemo.make, {
                  openModal: (function (param) {
                      return Curry._1(dispatch, /* Open */0);
                    }),
                  isModalOpened: state.isModalOpened
                }), state.isModalOpened ? React.createElement(Modal$ReasonHasuraDemo.make, {
                    closeModal: (function (param) {
                        return Curry._1(dispatch, /* Close */1);
                      })
                  }) : null, React.createElement(PostsList$ReasonHasuraDemo.make, {}), React.createElement(Counter$ReasonHasuraDemo.make, {}));
}

var make = App;

exports.make = make;
/* react Not a pure module */
