// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/legacy/ReactDOMRe.bs.js");
var ReactApollo = require("react-apollo");
var ServiceWorker = require("./serviceWorker");
var ReactHooks = require("@apollo/react-hooks");
var App$ReasonHasuraDemo = require("./App.bs.js");
var ApolloClient$ReasonHasuraDemo = require("./ApolloClient.bs.js");

import './index.css'
;

import 'animate.css'
;

function register_service_worker(prim) {
  ServiceWorker.register();
  
}

function unregister_service_worker(prim) {
  ServiceWorker.unregister();
  
}

var client = ApolloClient$ReasonHasuraDemo.makeApolloClient(undefined);

ReactDOMRe.renderToElementWithId(React.createElement(ReactApollo.ApolloProvider, {
          client: client,
          children: React.createElement(ReactHooks.ApolloProvider, {
                client: client,
                children: React.createElement(App$ReasonHasuraDemo.make, {})
              })
        }), "root");

ServiceWorker.unregister();

exports.register_service_worker = register_service_worker;
exports.unregister_service_worker = unregister_service_worker;
exports.client = client;
/*  Not a pure module */
