// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/legacy/ReactDOMRe.bs.js");
var ReactApollo = require("react-apollo");
var ServiceWorker = require("./serviceWorker");
var App$ReasonHasuraDemo = require("./App.bs.js");
var Client$ReasonHasuraDemo = require("./Client.bs.js");

import './index.css'
;

import 'animate.css'
;

function register_service_worker(prim) {
  ServiceWorker.register();
  
}

function unregister_service_worker(prim) {
  ServiceWorker.unregister();
  
}

ReactDOMRe.renderToElementWithId(React.createElement(ReactApollo.ApolloProvider, {
          client: Client$ReasonHasuraDemo.instance,
          children: React.createElement(App$ReasonHasuraDemo.make, {})
        }), "root");

ServiceWorker.unregister();

exports.register_service_worker = register_service_worker;
exports.unregister_service_worker = unregister_service_worker;
/*  Not a pure module */
