// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var AddPostForm$ReasonHasuraDemo = require("./AddPostForm.bs.js");

function Modal(Props) {
  var closeModal = Props.closeModal;
  return React.createElement("div", {
              className: "absolute border w-11/12 z-10 bg-gray-100 shadow-md p-5 modal-center animated zoomInUp",
              onClick: (function ($$event) {
                  $$event.stopPropagation();
                  
                })
            }, React.createElement(AddPostForm$ReasonHasuraDemo.make, {
                  closeModal: closeModal
                }));
}

var make = Modal;

exports.make = make;
/* react Not a pure module */
