// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Header$ReasonHasuraDemo from "./components/Header.bs.js";
import * as Counter$ReasonHasuraDemo from "./components/Counter.bs.js";

function App(Props) {
  var match = React.useReducer((function (param, action) {
          if (action) {
            return {
                    isModalOpened: false
                  };
          } else {
            return {
                    isModalOpened: true
                  };
          }
        }), {
        isModalOpened: false
      });
  var dispatch = match[1];
  return React.createElement("div", {
              onClick: (function (param) {
                  return Curry._1(dispatch, /* Close */1);
                })
            }, React.createElement(Header$ReasonHasuraDemo.make, {
                  openModal: (function (param) {
                      return Curry._1(dispatch, /* Open */0);
                    }),
                  isModalOpened: match[0].isModalOpened
                }), React.createElement(Counter$ReasonHasuraDemo.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
