// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var ReactApollo = require("react-apollo");
var ReactHooks = require("@apollo/react-hooks");
var App$ReasonHasuraHooksDevto = require("./App.bs.js");
var Client$ReasonHasuraHooksDevto = require("./Client.bs.js");

((require('./styles.css')));

ReactDOMRe.renderToElementWithId(React.createElement(ReactApollo.ApolloProvider, {
          client: Client$ReasonHasuraHooksDevto.instance,
          children: React.createElement(ReactHooks.ApolloProvider, {
                client: Client$ReasonHasuraHooksDevto.instance,
                children: React.createElement(App$ReasonHasuraHooksDevto.make, { })
              })
        }), "root");

/*  Not a pure module */
